local M = {}
local colors = require("dawnbreaker.utils.color").COLORS

M.url = "https://github.com/Bekaboo/dropbar.nvim"

function M.get()
	return {
		DropBarMenuHoverEntry = { link = "Visual" },
		DropBarMenuHoverIcon = { reverse = true },
		DropBarMenuHoverSymbol = { bold = true },
		DropBarIconUISeparator = { fg = colors.GRAY },
		DropBarKindArray = { fg = colors.DEFAULT },
		DropBarKindBoolean = { fg = colors.DEFAULT },
		DropBarKindBreakStatement = { fg = colors.DEFAULT },
		DropBarKindCall = { fg = colors.DEFAULT },
		DropBarKindCaseStatement = { fg = colors.DEFAULT },
		DropBarKindClass = { fg = colors.DEFAULT },
		DropBarKindConstant = { fg = colors.DEFAULT },
		DropBarKindConstructor = { fg = colors.DEFAULT },
		DropBarKindContinueStatement = { fg = colors.DEFAULT },
		DropBarKindDeclaration = { fg = colors.DEFAULT },
		DropBarKindDelete = { fg = colors.DEFAULT },
		DropBarKindDoStatement = { fg = colors.DEFAULT },
		DropBarKindElseStatement = { fg = colors.DEFAULT },
		DropBarKindEnum = { fg = colors.DEFAULT },
		DropBarKindEnumMember = { fg = colors.DEFAULT },
		DropBarKindEvent = { fg = colors.DEFAULT },
		DropBarKindField = { fg = colors.DEFAULT },
		DropBarKindFile = { fg = colors.DEFAULT },
		DropBarKindFolder = { fg = colors.DEFAULT },
		DropBarKindForStatement = { fg = colors.DEFAULT },
		DropBarKindFunction = { fg = colors.DEFAULT },
		DropBarKindIdentifier = { fg = colors.DEFAULT },
		DropBarKindIfStatement = { fg = colors.DEFAULT },
		DropBarKindInterface = { fg = colors.DEFAULT },
		DropBarKindKeyword = { fg = colors.DEFAULT },
		DropBarKindList = { fg = colors.DEFAULT },
		DropBarKindMacro = { fg = colors.DEFAULT },
		DropBarKindMarkdownH1 = { fg = colors.DEFAULT },
		DropBarKindMarkdownH2 = { fg = colors.DEFAULT },
		DropBarKindMarkdownH3 = { fg = colors.DEFAULT },
		DropBarKindMarkdownH4 = { fg = colors.DEFAULT },
		DropBarKindMarkdownH5 = { fg = colors.DEFAULT },
		DropBarKindMarkdownH6 = { fg = colors.DEFAULT },
		DropBarKindMethod = { fg = colors.DEFAULT },
		DropBarKindModule = { fg = colors.DEFAULT },
		DropBarKindNamespace = { fg = colors.DEFAULT },
		DropBarKindNull = { fg = colors.DEFAULT },
		DropBarKindNumber = { fg = colors.DEFAULT },
		DropBarKindObject = { fg = colors.DEFAULT },
		DropBarKindOperator = { fg = colors.DEFAULT },
		DropBarKindPackage = { fg = colors.DEFAULT },
		DropBarKindProperty = { fg = colors.DEFAULT },
		DropBarKindReference = { fg = colors.DEFAULT },
		DropBarKindRepeat = { fg = colors.DEFAULT },
		DropBarKindScope = { fg = colors.DEFAULT },
		DropBarKindSpecifier = { fg = colors.DEFAULT },
		DropBarKindStatement = { fg = colors.DEFAULT },
		DropBarKindString = { fg = colors.DEFAULT },
		DropBarKindStruct = { fg = colors.DEFAULT },
		DropBarKindSwitchStatement = { fg = colors.DEFAULT },
		DropBarKindType = { fg = colors.DEFAULT },
		DropBarKindTypeParameter = { fg = colors.DEFAULT },
		DropBarKindUnit = { fg = colors.DEFAULT },
		DropBarKindValue = { fg = colors.DEFAULT },
		DropBarKindVariable = { fg = colors.DEFAULT },
		DropBarKindWhileStatement = { fg = colors.DEFAULT },
	}
end

return M
