local M = {}
local colors = require("dawnbreaker.utils.color").COLORS

M.url = "https://github.com/NeogitOrg/neogit"

function M.get()
	return {
		NeogitBranch = { fg = colors.ORANGE, style = { "bold" } },
		NeogitRemote = { fg = colors.GREEN, style = { "bold" } },
		NeogitUnmergedInto = { link = "Function" },
		NeogitUnpulledFrom = { link = "Function" },
		NeogitObjectId = { link = "Comment" },
		NeogitStash = { link = "Comment" },
		NeogitRebaseDone = { link = "Comment" },
		NeogitHunkHeader = { bg = colors.BLUE_BG, fg = colors.BLUE_DARK },
		NeogitHunkHeaderHighlight = { bg = colors.BLUE_BG_LIGHT, fg = colors.BLUE },
		NeogitDiffContextHighlight = { bg = colors.SELECTION },
		NeogitDiffDeleteHighlight = { bg = colors.RED_BG, fg = colors.RED_LIGHT },
		NeogitDiffAddHighlight = { bg = colors.GREEN_BG, fg = colors.GREEN_LIGHT },
		NeogitDiffDelete = { bg = colors.RED_BG, fg = colors.RED_DARK },
		NeogitDiffAdd = { bg = colors.GREEN_BG, fg = colors.GREEN_DARK },
		NeogitCommitViewHeader = { bg = colors.BLUE_BG_LIGHT, fg = colors.BLUE_LIGHT },
		NeogitChangeModified = { fg = colors.BLUE, style = { "bold" } },
		NeogitChangeDeleted = { fg = colors.RED, style = { "bold" } },
		NeogitChangeAdded = { fg = colors.GREEN, style = { "bold" } },
		NeogitChangeRenamed = { fg = colors.PURPLE, style = { "bold" } },
		NeogitChangeUpdated = { fg = colors.ORANGE, style = { "bold" } },
		NeogitChangeCopied = { fg = colors.PINK, style = { "bold" } },
		NeogitChangeBothModified = { fg = colors.YELLOW, style = { "bold" } },
		NeogitChangeNewFile = { fg = colors.GREEN, style = { "bold" } },
		NeogitUntrackedfiles = { fg = colors.PURPLE, style = { "bold" } },
		NeogitUnstagedchanges = { fg = colors.PURPLE, style = { "bold" } },
		NeogitUnmergedchanges = { fg = colors.PURPLE, style = { "bold" } },
		NeogitUnpulledchanges = { fg = colors.PURPLE, style = { "bold" } },
		NeogitRecentcommits = { fg = colors.PURPLE, style = { "bold" } },
		NeogitStagedchanges = { fg = colors.PURPLE, style = { "bold" } },
		NeogitStashes = { fg = colors.PURPLE, style = { "bold" } },
		NeogitRebasing = { fg = colors.PURPLE, style = { "bold" } },
		NeogitNotificationInfo = { fg = colors.BLUE },
		NeogitNotificationWarning = { fg = colors.YELLOW },
		NeogitNotificationError = { fg = colors.RED },
		NeogitGraphRed = { fg = colors.RED },
		NeogitGraphWhite = { fg = colors.BG },
		NeogitGraphYellow = { fg = colors.YELLOW },
		NeogitGraphGreen = { fg = colors.GREEN },
		NeogitGraphCyan = { fg = colors.BLUE },
		NeogitGraphBlue = { fg = colors.BLUE },
		NeogitGraphPurple = { fg = colors.PURPLE },
		NeogitGraphGray = { fg = colors.GRAY },
		NeogitGraphOrange = { fg = colors.ORANGE },
		NeogitGraphBoldRed = { fg = colors.RED, style = { "bold" } },
		NeogitGraphBoldWhite = { fg = colors.DEFAULT, style = { "bold" } },
		NeogitGraphBoldYellow = { fg = colors.YELLOW, style = { "bold" } },
		NeogitGraphBoldGreen = { fg = colors.GREEN, style = { "bold" } },
		NeogitGraphBoldCyan = { fg = colors.BLUE, style = { "bold" } },
		NeogitGraphBoldBlue = { fg = colors.BLUE, style = { "bold" } },
		NeogitGraphBoldPurple = { fg = colors.PURPLE, style = { "bold" } },
		NeogitGraphBoldGray = { fg = colors.GRAY, style = { "bold" } },
		NeogitDiffContext = { bg = colors.BG },
		NeogitPopupBold = { style = { "bold" } },
		NeogitPopupSwitchKey = { fg = colors.PURPLE },
		NeogitPopupOptionKey = { fg = colors.PURPLE },
		NeogitPopupConfigKey = { fg = colors.PURPLE },
		NeogitPopupActionKey = { fg = colors.PURPLE },
		NeogitFilePath = { fg = colors.BLUE, style = { "italic" } },
		NeogitDiffHeader = { bg = colors.BG, fg = colors.BLUE, style = { "bold" } },
		NeogitDiffHeaderHighlight = { bg = colors.BG, fg = colors.ORANGE, style = { "bold" } },
		NeogitUnpushedTo = { fg = colors.PURPLE, style = { "bold" } },
		NeogitFold = { fg = "NONE", bg = "NONE" },
		NeogitSectionHeader = { fg = colors.PURPLE, style = { "bold" } },
		NeogitTagName = { fg = colors.YELLOW },
		NeogitTagDistance = { fg = colors.BLUE },
		NeogitWinSeparator = { link = "WinSeparator" },
	}
end

return M
