local M = {}
local colors = require("dawnbreaker.utils.color").COLORS

M.url = "https://github.com/pwntester/octo.nvim"

function M.get()
	return {
		OctoGrey = { fg = colors.BG },
		OctoBlue = { fg = colors.BLUE },
		OctoGreen = { fg = colors.GREEN },
		OctoRed = { fg = colors.RED },
		OctoPurple = { fg = colors.PURPLE },
		OctoYellow = { fg = colors.YELLOW },
		OctoDirty = { link = "ErrorMsg" },
		OctoIssueTitle = { link = "PreProc" },
		OctoIssueId = { link = "Question" },
		OctoEmpty = { link = "Comment" },
		OctoFloat = { link = "NormalNC" },
		OctoDate = { link = "Comment" },
		OctoSymbol = { link = "Comment" },
		OctoTimelineItemHeading = { link = "Comment" },
		OctoDetailsLabel = { link = "Title" },
		OctoMissingDetails = { link = "Comment" },
		OctoDetailsValue = { link = "Identifier" },
		OctoDiffHunkPosition = { link = "NormalFloat" },
		OctoCommentLine = { link = "TabLineSel" },
		OctoViewer = { fg = colors.BG, bg = colors.BLUE },
		OctoBubble = { fg = colors.DEFAULT, bg = colors.BG },
		OctoBubbleGrey = { fg = colors.DEFAULT, bg = colors.BG },
		OctoBubbleDelimiterGrey = { fg = colors.BG },
		OctoBubbleGreen = { fg = colors.BG, bg = colors.GREEN },
		OctoBubbleDelimiterGreen = { fg = colors.GREEN },
		OctoBubbleBlue = { fg = colors.BG, bg = colors.CYAN },
		OctoBubbleDelimiterBlue = { fg = colors.CYAN },
		OctoBubbleYellow = { fg = colors.BG, bg = colors.YELLOW },
		OctoBubbleDelimiterYellow = { fg = colors.YELLOW },
		OctoBubbleRed = { fg = colors.BG, bg = colors.RED },
		OctoBubbleDelimiterRed = { fg = colors.RED },
		OctoBubblePurple = { fg = colors.BG, bg = colors.PURPLE },
		OctoBubbleDelimiterPurple = { fg = colors.PURPLE },
		OctoUser = { link = "OctoBubble" },
		OctoUserViewer = { link = "OctoViewer" },
		OctoReaction = { link = "OctoBubble" },
		OctoReactionViewer = { link = "OctoViewer" },
		OctoPassingTest = { link = "OctoGreen" },
		OctoFailingTest = { link = "OctoRed" },
		OctoPullAdditions = { link = "OctoGreen" },
		OctoPullDeletions = { link = "OctoRed" },
		OctoPullModifications = { fg = colors.ORANGE },
		OctoStateOpen = { fg = colors.GREEN, bg = colors.BG },
		OctoStateOpenFloat = { fg = colors.GREEN, bg = colors.BG },
		OctoStateClosed = { fg = colors.RED, bg = colors.BG },
		OctoStateClosedFloat = { fg = colors.RED, bg = colors.BG },
		OctoStateMerged = { fg = colors.PURPLE, bg = colors.BG },
		OctoStateMergedFloat = { fg = colors.PURPLE, bg = colors.BG },
		OctoStatePending = { fg = colors.ORANGE, bg = colors.BG },
		OctoStatePendingFloat = { fg = colors.ORANGE, bg = colors.BG },
		OctoStateApproved = { link = "OctoStateOpen" },
		OctoStateApprovedFloat = { link = "OctoStateOpen" },
		OctoStateChangesRequested = { fg = colors.RED, bg = colors.BG },
		OctoStateChangesRequestedFloat = { fg = colors.RED, bg = colors.BG },
		OctoStateCommented = { link = "Normal" },
		OctoStateCommentedFloat = { link = "Normal" },
		OctoStateDismissed = { link = "OctoStateClosed" },
		OctoStateDismissedFloat = { link = "OctoStateClosed" },
		OctoStateSubmittedBubble = { link = "OctoBubbleGreen" },
		OctoFilePanelCounter = { fg = colors.BLUE, style = { "bold" } },
		OctoFilePanelTitle = { fg = colors.BLUE, style = { "bold" } },
		OctoFilePanelFileName = {},
		OctoNormalFront = { fg = colors.DEFAULT },
		OctoYellowFloat = { fg = colors.YELLOW, bg = colors.BG },
		OctoPurpleFloat = { fg = colors.PURPLE, bg = colors.BG },
		OctoRedFloat = { fg = colors.RED, bg = colors.BG },
		OctoGreenFloat = { fg = colors.GREEN, bg = colors.BG },
		OctoGreyFloat = { fg = colors.DEFAULT, bg = colors.BG },
		OctoBlueFloat = { fg = colors.BLUE, bg = colors.BG },
	}
end

return M
