local M = {}
local colors = require("dawnbreaker.utils.color").COLORS

M.url = "https://github.com/folke/snacks.nvim"

function M.get()
	return {
		SnacksNormal = { link = "Normal" },
		SnacksWinBar = { link = "Title" },
		SnacksBackdrop = { link = "FloatShadow" },
		SnacksNormalNC = { link = "NormalFloat" },
		SnacksWinBarNC = { link = "SnacksWinBar" },
		SnacksNotifierInfo = { fg = colors.BLUE },
		SnacksNotifierIconInfo = { fg = colors.BLUE },
		SnacksNotifierTitleInfo = { fg = colors.BLUE, style = { "italic" } },
		SnacksNotifierFooterInfo = { link = "DiagnosticInfo" },
		SnacksNotifierBorderInfo = { fg = colors.BLUE },
		SnacksNotifierWarn = { fg = colors.YELLOW },
		SnacksNotifierIconWarn = { fg = colors.YELLOW },
		SnacksNotifierTitleWarn = { fg = colors.YELLOW, style = { "italic" } },
		SnacksNotifierBorderWarn = { fg = colors.YELLOW },
		SnacksNotifierFooterWarn = { link = "DiagnosticWarn" },
		SnacksNotifierDebug = { fg = colors.ORANGE },
		SnacksNotifierIconDebug = { fg = colors.ORANGE },
		SnacksNotifierTitleDebug = { fg = colors.ORANGE, style = { "italic" } },
		SnacksNotifierBorderDebug = { fg = colors.ORANGE },
		SnacksNotifierFooterDebug = { link = "DiagnosticHint" },
		SnacksNotifierError = { fg = colors.RED },
		SnacksNotifierIconError = { fg = colors.RED },
		SnacksNotifierTitleError = { fg = colors.RED, style = { "italic" } },
		SnacksNotifierBorderError = { fg = colors.RED },
		SnacksNotifierFooterError = { link = "DiagnosticError" },
		SnacksNotifierTrace = { fg = colors.PURPLE },
		SnacksNotifierIconTrace = { fg = colors.PURPLE },
		SnacksNotifierTitleTrace = { fg = colors.PURPLE, style = { "italic" } },
		SnacksNotifierBorderTrace = { fg = colors.PURPLE },
		SnacksNotifierFooterTrace = { link = "DiagnosticHint" },
		SnacksDashboardNormal = { link = "Normal" },
		SnacksDashboardDesc = { fg = colors.BLUE },
		SnacksDashboardFile = { fg = colors.PURPLE },
		SnacksDashboardDir = { link = "NonText" },
		SnacksDashboardFooter = { fg = colors.YELLOW, style = { "italic" } },
		SnacksDashboardHeader = { fg = colors.BLUE },
		SnacksDashboardIcon = { fg = colors.PINK, bold = true },
		SnacksDashboardKey = { fg = colors.ORANGE },
		SnacksDashboardTerminal = { link = "SnacksDashboardNormal" },
		SnacksDashboardSpecial = { link = "Special" },
		SnacksDashboardTitle = { link = "Title" },
		SnacksIndent = { fg = colors.SELECTION },
		SnacksIndentScope = { fg = colors.DEFAULT },
		SnacksPickerSelected = { fg = colors.DEFAULT, bg = "NONE", style = { "bold" } },
		SnacksPickerMatch = { fg = colors.BLUE },
		SnacksPicker = { link = "NormalFloat" },
		SnacksPickerBorder = { link = "FloatBorder" },
		SnacksPickerInputBorder = { link = "SnacksPickerBorder" },
		SnacksPickerInput = { link = "NormalFloat" },
		SnacksPickerPrompt = { fg = colors.PINK },
		SnacksPickerTitle = { fg = colors.BG, bg = colors.PURPLE },
		SnacksPickerPreviewTitle = { fg = colors.BG, bg = colors.GREEN },
		SnacksPickerInputTitle = { fg = colors.BG, bg = colors.RED },
		SnacksPickerListTitle = { fg = colors.BG, bg = colors.PURPLE },
	}
end

return M
